# Generated by Django 3.2.12 on 2022-04-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing_date', models.DateTimeField(verbose_name='ゲーム開催日時')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名前')),
                ('created_at', models.DateTimeField(verbose_name='作成日時')),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_records.game', verbose_name='game_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_records.user', verbose_name='user_id')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=25000)),
                ('point', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_records.game', verbose_name='game_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mahjong_records.user', verbose_name='user_id')),
            ],
        ),
    ]
