# Generated by Django 3.2.12 on 2022-04-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahjong_records', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGame',
        ),
    ]
